include: package:very_good_analysis/analysis_options.5.1.0.yaml

linter:
  rules:
    public_member_api_docs: false
    prefer_const_constructors: false
    unnecessary_library_directive: false
    avoid_positional_boolean_parameters: false
    prefer_const_literals_to_create_immutables: false